[build]
  command = "pnpm run build"
  publish = "out/renderer"

[[redirects]]
  from = "/api/ttml/*"
  to = "https://lyrics.focalors.ltd/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://music-api.focalors.ltd/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
